#!/bin/sh
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
python tsp.py instance_8.txt
