#!/bin/sh
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
python tsp.py instance_1.txt
