#!/bin/sh
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
python tsp.py instance_5.txt
