#!/bin/sh
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
python tsp.py instance_7.txt
