#!/bin/sh
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
python tsp.py instance_9.txt
