#!/bin/sh
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
python tsp.py instance_10.txt
