#!/bin/sh
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
python tsp.py instance_2.txt
