#!/bin/sh
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
python tsp.py instance_3.txt
