#!/bin/sh
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
python tsp.py instance_4.txt
