#!/bin/sh
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
python tsp.py instance_6.txt
